config/routes.rb
Spree::Core::Engine.routes.draw do
  get "static_translations/index"

  #get "static_pages/index"

  # Add your extension routes here
	Spree::Core::Engine.routes.draw do
    resources :static_translations
  #get "/static_translations"=> "StaticTranslations#index"

  #get "static_pages/index" 

		get "/price" => "home#price"
	  	match "users/:id/send_email" => "users#send_email", :as => "users_send_email"
      match "orders/:id/confirmation" => "orders#confirmation", :as => "orders_confirmation"
      match "orders/complete_order" => "orders#complete_order", :as => "complete_order"
      match "orders/process_order" => "orders#process_order", :as => "process_order"
      match "paypal_payment" => "orders#paypal_payment", :as => "orders_paypal_payment"
      match "payment_options" => "home#payment_options", :as => "home_payment_options"
      match "payment" => "users#payment"
      match "profile" => "users#profile"
      match "auctions" => "users#auctions"
      match "catalog" => "users#catalog"
      get "add_credit_card" => "users#add_credit_card", :as => "add_credit_card"
      get "credit_card_info" => "users#credit_card_info", :as => "credit_card_info"
      get "faq" => "users#faq", :as => "faq"
      resources :bids
     # get '/complete_order' => 'bids#complete_order'

#      get '/static_pages/index', :to => 'Admin/StaticPages#index'
#      get '/static_pages/new', :to => 'Admin/StaticPages#new' 
#      #post '/', :to => 'Admin/StaticPages#create'
      namespace :admin do
        resources :static_pages
        resources :categories
        resources :author_bios
         resources :navigations
        resources :custom_email_contents, except: [:show, :new]
        get '/sort_nav_up' => 'navigations#sort_nav_up'
        get '/sort_nav_down' =>'navigations#sort_nav_down'
        resources :products do
          resources :bids
        end
        get '/pendding_order' =>'products#pendding_order', :as => 'pendding_order'
      end
      
      resources :view_categories
      resources :follows do
        get :follow_product, on: :collection
      end
	end
end

app/controllers/spree/admin/static_pages_controller.rb
class Spree::Admin::StaticPagesController < Spree::Admin::BaseController
   skip_before_filter :authorize_admin, :only => :index
  
  def index
    @data =StaticContentPage.all
  end

  def new
    @static_page = StaticContentPage.new
  end



   def create
     # params[:category][:url] =  params[:category][:url].split("//").last
     static_page = StaticContentPage.create!(params[:static_content_page])
     if params[:lang] == "pl"
       static_page.translations.where(locale: "en").first.update_attribute(:title=> "",:description => "") if static_page.translations.where(locale: "en").first
       translation =  static_page.translations.create(locale: params[:lang], title: params[:static_content_page][:title],:description => params[:static_content_page][:description])
     end
     flash[:notice] = "Page created successfully"
     redirect_to  admin_static_pages_url
   end

   def edit
     @static_page = StaticContentPage.find(params[:id])
   end

  def update

    @static_page = StaticContentPage.find params[:id]
    if @static_page.update_attributes(params[:static_content_page])
      if params[:lang] == 'pl'
        translation =  @static_page.translations.find_or_initialize_by_locale(params[:lang])
        @static_page.translations.where(locale: "en").first.update_attributes(:title=> params[:english_title],
                                                                              :description => params[:english_description])
        translation.update_attributes(:title => params[:static_content_page][:title],:description => params[:static_content_page][:description])
      end
      flash[:notice] = "Static page updated successfully"
    else
      flash[:error] = "Error occured in updating page"
    end
    redirect_to admin_static_pages_url
  end

   def destroy
     @static_page = StaticContentPage.find params[:id]
     if @static_page.destroy
       flash[:notice] = "Page deleted successfully"
     else
       flash[:error] = "Error occurred while deleting page"
     end
     redirect_to admin_static_pages_url
   end

end

app/helpers/spree/admin/static_pages_helper.rb
module Spree::Admin::StaticPagesHelper
end

app/views/spree/admin/static_pages/edit.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:editing_faq) %>
<% end %>
<div class="left eight columns alpha" data-hook="admin_product_form_left">

  <% translations = @static_page.translations %>
  <%= form_for [:admin, @static_page], :url=> admin_static_page_path ,:method => :put do |f| %>
      <%= select_tag "lang", options_for_select([["en", :lang => translations.where(locale: "en").first.try(:title)],
                 ["pl", :lang => translations.where(locale: "pl").first.try(:title)] ]), id: "lang_dropdn" %>
      <fieldset class="no-border-top">
        <table class = "no_border">
          <tr class="no_border">
            <td class="no_border">
              <%= f.label :title%>
            </td>
            <td class="no_border">
              <%= f.text_field :title, required:true, value: @static_page.title %>
              <%= hidden_field_tag "english_title", translations.where(locale: "en").first.try(:title)%>
            </td>
          </tr>
          <tr>
            <td class="no_border">
              <%= f.label :description%>
            </td>
            <td class="no_border">

              <%= f.text_area :description, :rows => 5, :cols => 115 , value: @static_page.description  %>
              <%= hidden_field_tag "english_description", translations.where(locale: "en").first.try(:description)%>
            </td>
          </tr>


          <tr>
            <td class="no_border"></td>
            <td class="no_border" colspan= "2" style="float:right;">
              <%= f.submit 'Update' %>
            </td>
          </tr>
        </table>
      </fieldset>
  <% end %>
  <script>
      $("#lang_dropdn").change(function(e){
          selected = $("#lang_dropdn :selected");
          text = selected.attr('lang');
          $("#navigation_name").attr('value', text);
      });

  </script>

app/views/spree/admin/static_pages/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:listing_faqs) %>
<%end%>

<% content_for :page_actions do %>
    <li id="new_navigation_link">
      <%= button_link_to Spree.t(:new_faq), new_admin_static_page_path, {:icon => 'icon-plus', :id => 'new_admin_navigation' } %>
    </li>
<%end%>

<% if  @data.any? %>
    <table class="index" id="listing_navigations">
      <thead>
      <tr data-hook="navigation_index_headers">

        <th><%= Spree.t(:title) %></th>
        <th><%= Spree.t(:description) %></th>
        <th data-hook="navigation_index_headers" class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% count = 1%>
      <% @data.each do |staticpage| %>
          <tr data-hook="admin_navigation_index_rows" class="each_navigation">
            <td class="align-center"><%= count %> . <%= staticpage.title %></td>
            <td class="align-center"><%= raw staticpage.description %></td>
            <% count+=1%>
            <td class="actions" data-hook="navigation_index_row_actions_edit">
              <a href="<%=edit_admin_static_page_path(staticpage)%>" class="edit icon_link with-tip icon-edit no-text"></a>
            </td>
            <td class="actions" data-hook="navigation_index_row_actions">
              <a href="<%=admin_static_page_path(staticpage)%>" class="delete-resource icon_link with-tip icon-trash no-text" data-method="delete" data-action="destroy" data-confirm="Are you sure?"></a>
            </td>
      <% end %>
      </tr>
      </tbody>
    </table>
<% else %>
    <div class="no-object-found">
      <%= Spree.t(:no_results) %>
    </div>
<%end%>

app/views/spree/admin/static_pages/new.html.erb
<%= form_for [:admin, @static_page], :url=> admin_static_pages_path do |f| %>
<%= select_tag "lang", options_for_select(["en", "pl"])%>
<table class = "no_border">
    <tr class="no_border">
        <td class="no_border">
            <%= f.label :title %>
        </td>
        <td class="no_border">
            <%= f.text_field :title %>
        </td>
    </tr>
    <tr class="no_border">
        <td class="no_border">
            <%= f.label :Description %>
        </td>
        <td class="no_border">
            <%= f.text_area :description, :rows => 5, :cols => 115 %>
        </td>
    </tr>
    <tr>
    	<td class="no_border"></td>
        <td class="no_border" colspan= "2" style="float:right;">
            <%= f.submit 'Save' %>
        </td>
    </tr>
</table>
<% end %>