config/routes.rb
Spree::Core::Engine.routes.draw do
  get "static_translations/index"

  #get "static_pages/index"

  # Add your extension routes here
	Spree::Core::Engine.routes.draw do
    resources :static_translations
  #get "/static_translations"=> "StaticTranslations#index"

  #get "static_pages/index" 

		get "/price" => "home#price"
	  	match "users/:id/send_email" => "users#send_email", :as => "users_send_email"
      match "orders/:id/confirmation" => "orders#confirmation", :as => "orders_confirmation"
      match "orders/complete_order" => "orders#complete_order", :as => "complete_order"
      match "orders/process_order" => "orders#process_order", :as => "process_order"
      match "paypal_payment" => "orders#paypal_payment", :as => "orders_paypal_payment"
      match "payment_options" => "home#payment_options", :as => "home_payment_options"
      match "payment" => "users#payment"
      match "profile" => "users#profile"
      match "auctions" => "users#auctions"
      match "catalog" => "users#catalog"
      get "add_credit_card" => "users#add_credit_card", :as => "add_credit_card"
      get "credit_card_info" => "users#credit_card_info", :as => "credit_card_info"
      get "faq" => "users#faq", :as => "faq"
      resources :bids
     # get '/complete_order' => 'bids#complete_order'

#      get '/static_pages/index', :to => 'Admin/StaticPages#index'
#      get '/static_pages/new', :to => 'Admin/StaticPages#new' 
#      #post '/', :to => 'Admin/StaticPages#create'
      namespace :admin do
        resources :static_pages
        resources :categories
        resources :author_bios
         resources :navigations
        resources :custom_email_contents, except: [:show, :new]
        get '/sort_nav_up' => 'navigations#sort_nav_up'
        get '/sort_nav_down' =>'navigations#sort_nav_down'
        resources :products do
          resources :bids
        end
        get '/pendding_order' =>'products#pendding_order', :as => 'pendding_order'
      end
      
      resources :view_categories
      resources :follows do
        get :follow_product, on: :collection
      end
	end
end

app/models/spree/custom_email_content.rb
class Spree::CustomEmailContent < ActiveRecord::Base
   attr_accessible :name, :body, :language
   validates_uniqueness_of :name
   
   serialize :body, Hash

   def display_name
     names = {"confirmation_instructions" =>"Account Confirmation Instructions", "bid_accepted" => "Bid Accepted Email", 
     	      "confirm_email" => "Order Confirmation Email", "bid_placed_email" => "Bid Placed Email",
     	      "looser_email" => "Looser Email", "outbid_email" => "OutBid Email", 
     	      "winner_chosen_email" => "Winner Chosen Email"}
     names[self.name]
   end
end

app/controllers/spree/admin/custom_email_contents_controller.rb
class Spree::Admin::CustomEmailContentsController < Spree::Admin::BaseController
  
  def index
    @email_contents = Spree::CustomEmailContent.all
  end
  
  def new
    @email_content = Spree::CustomEmailContent.new
  end
  
  def create
    body = params[:custom_email_content].delete("body")
    @email_content =  Spree::CustomEmailContent.find_or_create_by_name_and_language(params[:custom_email_content][:name], params[:custom_email_content][:language])
    @email_content.update_attributes(params[:custom_email_content])
    @email_content.body[params[:custom_email_content][:language].to_sym] = body
    if @email_content.save
      flash[:notice] = "Email Content created successfully"
      redirect_to admin_custom_email_contents_path
    else
      flash[:error] = "Error creating in custom email content - " + @email_content.errors.full_messages.join(", ")
      render :action => "new"
    end
  end
  
  def edit
    @email_content = Spree::CustomEmailContent.find(params[:id])
  end
  
  def update
    body = params[:custom_email_content].delete("body")
    @email_content = Spree::CustomEmailContent.find params[:id]
    @email_content.update_attributes(params[:custom_email_content])
    if @email_content.update_attributes(params[:custom_email_content])
      @email_content.body[params[:custom_email_content][:language].to_sym] = body
      @email_content.save
      flash[:notice] = "Email Content updated successfully"
    else
      flash[:error] = "Error occured in updating Email Content"
    end
    redirect_to admin_custom_email_contents_path
  end
  
  def destroy
     @email_content = Spree::CustomEmailContent.find(params[:id])
    if @email_content.destroy
      flash[:notice] = "Email Content deleted successfully"
    else
      flash[:error] = "Error occurred while deleting Email Content"
    end
    redirect_to admin_custom_email_contents_path
  end
end

app/views/spree/admin/custom_email_contents/_form.html.erb
<%= form_for [:admin, @email_content] do |f| %>
<table class="no-border">
    <tr class="no=border">
        <td class="no-border">
            <%= f.label :type %>
        </td>
        <td class="no-border">
            <%= f.select :language, options_for_select([["en", :body => @email_content.body[:en]], ["pl", :body => @email_content.body[:pl]]],:selected => f.object.language) %>
        </td>
    </tr>
    <tr class="no=border">
        <td class="no-border">
            <%= f.label :name %>
        </td>
        <td class="no-border">
          <%#= f.select :name, options_for_select([["Account Confirmation Instructions", "confirmation_instructions"], ["Bid Accepted Email", "bid_accepted"], ["Order Confirmation Email", "confirm_email"], ["Bid Placed Email", "bid_placed_email"], ["Winner Chosen Email", "winner_chosen_email"]], :selected =>  f.object.name) %>
          <%= f.object.display_name %>
        </td>
    </tr>
    <tr class="no=border">
        <td class="no-border">
            <%= f.label :body %>
        </td>
        <td class="no-border taget">
            <%= f.text_area :body, :id => "email_content", value: @email_content.body[I18n.locale].present? ? @email_content.body[I18n.locale] : "" %>
            <p></p>Use the following short codes in the text to set their values accordingly:</p> 
            <div id="confirmation_instructions" class="short_codes" style="display: none;">
              <p>User Email: #user_email</p>
              <p>Confirm Account Link on signup: #confirm_account_link</p>
            </div>
            <div id="confirm_email" class="short_codes" style="display: none;">
              n/a
            </div>
            <div id="bid_accepted" class="short_codes" style="display: none;">
              <% ['#order_number', '#order_firstname', '#order_lastname', "#order_address1", "#order_address2", "#order_city", '#order_state', "#order_phone"].each do |code| %>
                <% case code %>
                  <% when "#order_number" %>
                    <p> Order Number: <%=code%></p>
                  <% when "#order_firstname" %>
                    <p> First Name: <%=code%></p>
                  <% when "#order_lastname" %>
                    <p> Last Name: <%=code%></p>
                  <% when "#order_address1" %>
                    <p> Address 1: <%=code%></p>
                  <% when "#order_address2" %>
                    <p> Address 2: <%=code%></p>
                  <% when "#order_city" %>
                    <p> City: <%=code%></p>
                  <% when "#order_state" %>
                    <p> State: <%=code%></p>
                  <% when "#order_phone" %>
                    <p> Phone: <%=code%></p>
                <% end%>
              <% end %>
            </div>
          <%if f.object.name == "bid_placed_email" %>
            <div id="bid_placed_email" class="short_codes" >
              <p>Product Name: #product</p>
              <p>Product URL: #url_of_product</p>
            </div>
          <%elsif f.object.name == "winner_chosen_email" %>
            <div id="winner_chosen_email" class="short_codes">
              <p>Product URL: #product</p>
              <p>Payment URL: #payment</p>
            </div>
          <%elsif f.object.name == "outbid_email" %>
            <div id="outbid_email" class="short_codes">
              <p>Product Name: #product</p>
              <p>Product URL: #url_of_product</p>
            </div>
          <%elsif f.object.name == "looser_email" %>
            <div id="looser_email" class="short_codes">
              <p>Product Name: #product</p>
              <p>Product URL: #url_of_product</p>
            </div>
          <%end%>
        </td>
        
    </tr>
     <tr>
        <td class="no_border"></td>
        <td class="no_border" colspan= "2" style="float:right;">
            <%= f.submit 'Save' %>
        </td>
    </tr>
 </table>
<% end %>

<script>
  $('#custom_email_content_language').change(function(e){
    selected = $('#custom_email_content_language :selected');
    $('#email_content').attr('value', selected.attr('body'));
  });
  $("#custom_email_content_name").change(function(e){
    id = "#" + $(this).val();
    $(".short_codes").hide();
    $(id).show();
  });
</script>

app/views/spree/admin/custom_email_contents/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_email_content) %>
<% end %>
<%= render :partial => "form"%>

app/views/spree/admin/custom_email_contents/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_email_contents) %>
<%end%>

<% content_for :page_actions do %>
  <!--<li id="new_navigation_link">-->
  <!--<%#= button_link_to Spree.t(:new_email_content), new_admin_custom_email_content_path, {:icon => 'icon-plus' } %>-->
  <!--</li>-->
<%end%> 

<% if @email_contents.any? %>
  <table class="index" id="listing_navigations">
    <thead>
        <tr data-hook="navigation_index_headers">
            <th><%= Spree.t(:name) %></th>
            <th><%= Spree.t(:body) %></th>
            <th data-hook="navigation_index_headers" class="actions"></th>
        </tr>
    </thead>
    <tbody>
        <% @email_contents.each do |email|%>
          <tr data-hook="admin_navigation_index_rows" class="each_navigation">
            <td class="align-center"><%= Spree.t(email.name) %></td>
            <td class="align-center"><%= email.body[I18n.locale].html_safe %></td>
            <td class="actions" data-hook="navigation_index_row_actions_edit">
              <a href="<%=edit_admin_custom_email_content_path(email)%>" class="edit icon_link with-tip icon-edit no-text"></a>
            </td>
            <!--<td class="actions" data-hook="navigation_index_row_actions">-->
              <!--<a href="<%#=admin_custom_email_content_path(email)%>" class="delete-resource icon_link with-tip icon-trash no-text" data-method="delete" data-action="destroy" data-confirm="Are you sure?"></a>-->
            <!--</td>-->
         <% end %>
           </tr>
    </tbody>
  </table>
<% else %>
  <div class="no-object-found">
    <%= Spree.t(:no_results) %>
  </div>
<%end%>

app/views/spree/admin/custom_email_contents/new.html.erb
<%= render :partial => "form"%>