config/routes.rb
Spree::Core::Engine.routes.draw do
  get "static_translations/index"

  #get "static_pages/index"

  # Add your extension routes here
	Spree::Core::Engine.routes.draw do
    resources :static_translations
  #get "/static_translations"=> "StaticTranslations#index"

  #get "static_pages/index" 

		get "/price" => "home#price"
	  	match "users/:id/send_email" => "users#send_email", :as => "users_send_email"
      match "orders/:id/confirmation" => "orders#confirmation", :as => "orders_confirmation"
      match "orders/complete_order" => "orders#complete_order", :as => "complete_order"
      match "orders/process_order" => "orders#process_order", :as => "process_order"
      match "paypal_payment" => "orders#paypal_payment", :as => "orders_paypal_payment"
      match "payment_options" => "home#payment_options", :as => "home_payment_options"
      match "payment" => "users#payment"
      match "profile" => "users#profile"
      match "auctions" => "users#auctions"
      match "catalog" => "users#catalog"
      get "add_credit_card" => "users#add_credit_card", :as => "add_credit_card"
      get "credit_card_info" => "users#credit_card_info", :as => "credit_card_info"
      get "faq" => "users#faq", :as => "faq"
      resources :bids
     # get '/complete_order' => 'bids#complete_order'

#      get '/static_pages/index', :to => 'Admin/StaticPages#index'
#      get '/static_pages/new', :to => 'Admin/StaticPages#new' 
#      #post '/', :to => 'Admin/StaticPages#create'
      namespace :admin do
        resources :static_pages
        resources :categories
        resources :author_bios
         resources :navigations
        resources :custom_email_contents, except: [:show, :new]
        get '/sort_nav_up' => 'navigations#sort_nav_up'
        get '/sort_nav_down' =>'navigations#sort_nav_down'
        resources :products do
          resources :bids
        end
        get '/pendding_order' =>'products#pendding_order', :as => 'pendding_order'
      end
      
      resources :view_categories
      resources :follows do
        get :follow_product, on: :collection
      end
	end
end

app/models/spree/author_bio.rb
class Spree::AuthorBio < ActiveRecord::Base
  attr_accessible :name, :biography
  validates :name, presence: true, uniqueness: true

  has_many :products, :class_name => "Spree::Product"
  has_many :photos, as: :imageable, :class_name => "Spree::Photo", :dependent => :destroy

  translates :name ,:biography

end

app/controllers/spree/admin/author_bios_controller.rb
class Spree::Admin::AuthorBiosController < Spree::Admin::BaseController
  
  def index
    @bios = Spree::AuthorBio.all
  end
  
  def new
    @bio = Spree::AuthorBio.new
  end

  def create
    author_bio = Spree::AuthorBio.create!(params[:author_bio])
    if params[:lang] == "pl"
      author_bio.translations.where(locale: "en").first.update_attribute(:name=> "" ,:biography => "" ) if author_bio.translations.where(locale: "en").first
      translation =  author_bio.translations.create(locale: params[:lang], name: params[:author_bio][:name], biography:params[:author_bio][:biography] )
    end
    flash[:notice] = "Bio created successfully"
    redirect_to admin_author_bios_path
  end
  
  def edit
    @bio = Spree::AuthorBio.find params[:id]
  end
  

  def update
    @bio = Spree::AuthorBio.find params[:id]
    if @bio.update_attributes(params[:author_bio])
      if params[:lang] == 'pl'
        translation =  @bio.translations.find_or_initialize_by_locale(params[:lang])
        @bio.translations.where(locale: "en").first.update_attributes(:name => params[:english_name],:biography => params[:english_bio_description] )
        translation.update_attributes(:name => params[:author_bio][:name],:biography => params[:author_bio][:biography])
      end
      flash[:notice] = "Bio updated successfully"
    else
      flash[:error] = "Error occured in updating bio"
    end
    redirect_to admin_author_bios_path
  end
  
  def destroy
    @bio = Spree::AuthorBio.find params[:id]
    if @bio.destroy
      flash[:notice] = "Bio deleted successfully"
    else
      flash[:error] = "Error occured in deleting bio"
    end
    redirect_to admin_author_bios_path
  end
  
end

app/helpers/spree/admin/author_bios_helper.rb
module Spree::Admin::AuthorBiosHelper
end

app/views/spree/admin/author_bios/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_biography) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_biographies_list), admin_author_bios_path, :icon => 'icon-arrow-left' %></li>
  <li id="new_bio_link">
    <%= button_link_to Spree.t(:new_biography), new_admin_author_bio_path, {:icon => 'icon-plus', :id => 'admin_new_biography' } %>
  </li>
<% end %>
<% translations = @bio.translations %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @bio } %>

<%= form_for [:admin, @bio], :method => :put, :html => { :multipart => true } do |f| %>
    <%= select_tag "lang", options_for_select([["en", :lang => translations.where(locale: "en").first.try(:name)],["pl",
                               :lang => translations.where(locale: "pl").first.try(:name)] ]), id: "lang_dropdn" %>

    <fieldset class="no-border-top">
    <table class = "no_border">
    <tr class="no_border">
        <td class="no_border">
            <%= f.label :name %>
        </td>
        <td class="no_border">
            <%= f.text_field :name %>
          <%= hidden_field_tag "english_name", translations.where(locale: "en").first.try(:name)%>
        </td>
    </tr>
    <tr class="no_border">
        <td class="no_border">
            <%= f.label :biography %>
        </td>
        <td class="no_border">
            <%= f.text_area :biography, :id => "bio_description" %>
            <%= hidden_field_tag "english_bio_description", translations.where(locale: "en").first.try(:biography)%>
        </td>
    </tr>
    <tr>
    	<td class="no_border"></td>
        <td class="no_border" colspan= "2" style="float:right;">
            <%= f.submit 'Update' %>
        </td>
    </tr>
</table>
  </fieldset>
<% end %>

app/views/spree/admin/author_bios/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_biographies) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_bio_link">
    <%= button_link_to Spree.t(:new_biography), new_admin_author_bio_path, {:icon => 'icon-plus', :id => 'admin_new_biography' } %>
  </li>
<% end %>

<% if @bios.any? %>
  <table class="index" id="listing_bios">
    <thead>
      <tr data-hook="admin_bios_index_headers">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:biography) %></th>
        <th data-hook="admin_bios_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @bios.each do |bio| %>
          <tr data-hook="admin_bios_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="align-center"><%= link_to bio.try(:name), edit_admin_author_bio_path(bio) %></td>
            <td class="align-center"><%= bio.biography.html_safe %></td>
            <td class="actions" data-hook="navigation_index_row_actions_edit">
              <a href="<%=edit_admin_author_bio_path(bio)%>" class="edit icon_link with-tip icon-edit no-text"></a>
            </td>
            <td class="actions" data-hook="admin_bios_index_row_actions">
              <a href="<%=admin_author_bio_path(bio)%>" class="delete-resource icon_link with-tip icon-trash no-text" data-method="delete" data-action="destroy" data-confirm="Are you sure?"></a>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= Spree.t(:no_results) %>
  </div>
<% end %>

app/views/spree/admin/author_bios/new.html.erb
<%= form_for [:admin, @bio] do |f| %>
<%= select_tag "lang", options_for_select(["en", "pl"])%>
<table class = "no_border">
    <tr class="no_border">
        <td class="no_border">
            <%= f.label :name %>
        </td>
        <td class="no_border">
            <%= f.text_field :name %>
        </td>
    </tr>
    <tr class="no_border">
        <td class="no_border">
            <%= f.label :biography %>
        </td>
        <td class="no_border">
            <%= f.text_area :biography, :id => "bio_description" %>
        </td>
    </tr>
    <tr>
    	<td class="no_border"></td>
        <td class="no_border" colspan= "2" style="float:right;">
            <%= f.submit 'Save' %>
        </td>
    </tr>
</table>
<% end %>